import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import SubNavbar from "../components/SubNavbar";

export default function Tab() {
  const router = useRouter();
  const { tab } = router.query;
  console.log(tab);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-sans">
        <Navbar />
        <SubNavbar tab={tab} />
      </main>
    </div>
  );
}
