import Head from "next/head";
import Navbar from "../components/Navbar";
import SubNavbar from "../components/SubNavbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-sans">
        <Navbar />
        <SubNavbar />
      </main>
    </div>
  );
}
